//  <auto-generated/> 


using Rido.Mqtt.IoTHubPnPClient;
using Rido.Mqtt.PnPApi;

namespace dtmi_rido_pnp
{
    public class memmon : BaseIoTHubClient
    {
        public const string ModelId = "dtmi:rido:pnp:memmon;1";

        public ReadOnlyProperty<DateTime> Property_started;
        public WritableProperty<bool> Property_enabled;
        public WritableProperty<int> Property_interval;
        public Telemetry<double> Telemetry_workingSet;
        public Command<Cmd_getRuntimeStats_Request, Cmd_getRuntimeStats_Response> Command_getRuntimeStats;

        public memmon(IMqttConnection c, ConnectionSettings cs) : base(c, cs)
        {
            Property_started = new ReadOnlyProperty<DateTime>(base.updateTwinBinder, "started");
            Property_interval = new WritableProperty<int>(this.updateTwinBinder, new PropertyUpdateCallbackBinder<int>(c, "interval"), "interval");
            Property_enabled = new WritableProperty<bool>(this.updateTwinBinder, new PropertyUpdateCallbackBinder<bool>(c, "enabled"), "enabled");
            Telemetry_workingSet = new Telemetry<double>(c, "workingSet");
            Command_getRuntimeStats = new Command<Cmd_getRuntimeStats_Request, Cmd_getRuntimeStats_Response>(c, "getRuntimeStats");
        }
    }

    public enum DiagnosticsMode
    {
        minimal = 0,
        complete = 1,
        full = 2
    }

    public class Cmd_getRuntimeStats_Request : IBaseCommandRequest<Cmd_getRuntimeStats_Request>
    {
        public DiagnosticsMode DiagnosticsMode { get; set; }

        public Cmd_getRuntimeStats_Request DeserializeBody(string payload)
        {
            return new Cmd_getRuntimeStats_Request()
            {
                DiagnosticsMode = System.Text.Json.JsonSerializer.Deserialize<DiagnosticsMode>(payload)
            };
        }
    }

    public class Cmd_getRuntimeStats_Response : BaseCommandResponse
    {
        public Dictionary<string, string> diagnosticResults { get; set; } = new Dictionary<string, string>();
    }
}
